config/routes.rb
Rails.application.routes.draw do
  get '/display', to: 'display_api#display'
  #####Seccion del API
  namespace :api do
    resources :orden_compras
  end
  #####
  get 'aux_bodobra', to: 'reg_aux#bodobra'
  get 'aux_bodcentral', to: 'reg_aux#bodcentral'
  get 'aux_personal', to: 'reg_aux#personal'
  post 'aux_bodobra', to: 'reg_aux#bo_create'
  post 'aux_bodcentral', to: 'reg_aux#bc_create'
  post 'aux_personal', to: 'reg_aux#po_create'
  get 'testmail', to: 'testmail#index'
  get '/materiales', to: 'materiales#index'
  get 'materiales/agregar'
  get 'materiales/peticion'
  get '/inventario', to: 'inventario#ver'
  get '/inventario/agregar', to: 'inventario#agregar'
  post '/inventario/agregar', to: 'inventario#add'
  get '/inventario/sacar', to: 'inventario#sacar'
  post '/inventario/sacar/update', to: 'inventario#update_sacar'
  post '/solicituds/:id/add', to: 'solicituds#add'
  post '/solicituds/:id/add_create', to: 'solicituds#add_create'
  post '/solicituds/:id/enviar', to: 'solicituds#enviar'
  post '/solicituds/responder', to: 'solicituds#responder'
  post '/solicituds/confirmar', to: 'solicituds#confirmar'
  post '/solicituds/confirmar/action', to: 'solicituds#action_confirmar'
  post '/solicituds/responder/envio', to: 'solicituds#envio_solicitud', defaults: { :format => 'json' }
  resources :materials
  resources :inventario_centrals
  resources :abastecimiento_obras
  resources :abastecimiento_centrals
  resources :bodega_centrals
  resources :inventario_obras
  resources :bodega_obras
  resources :proveedors
  resources :orden_compras
  resources :encargado_compras
  resources :bodeguero_centrals
  resources :bodeguero_obras
  resources :personal_obras
  resources :solicituds
  root    'static_pages#home'
  get     '/help', to: 'static_pages#help'
  get     '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup', to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
  get     '/operations', to: 'operations#center'
  get     'home/index'

  resources :users
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/encargado_compra.rb
class EncargadoCompra < ApplicationRecord
  belongs_to :user, inverse_of: :encargado_compras
  validates_presence_of :user
  has_one :bodeguero_central
  has_many :proveedors
  has_many :orden_compras
end

app/controllers/encargado_compras_controller.rb
class EncargadoComprasController < ApplicationController
  before_action :set_encargado_compra, only: [:show, :edit, :update, :destroy]

  # GET /encargado_compras
  # GET /encargado_compras.json
  def index
    @encargado_compras = EncargadoCompra.all
  end

  # GET /encargado_compras/1
  # GET /encargado_compras/1.json
  def show
  end

  # GET /encargado_compras/new
  def new
    @encargado_compra = EncargadoCompra.new
  end

  # GET /encargado_compras/1/edit
  def edit
  end

  # POST /encargado_compras
  # POST /encargado_compras.json
  def create
    @encargado_compra = EncargadoCompra.new(encargado_compra_params)

    respond_to do |format|
      if @encargado_compra.save
        format.html { redirect_to @encargado_compra, notice: 'Encargado compra was successfully created.' }
        format.json { render :show, status: :created, location: @encargado_compra }
      else
        format.html { render :new }
        format.json { render json: @encargado_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encargado_compras/1
  # PATCH/PUT /encargado_compras/1.json
  def update
    respond_to do |format|
      if @encargado_compra.update(encargado_compra_params)
        format.html { redirect_to @encargado_compra, notice: 'Encargado compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @encargado_compra }
      else
        format.html { render :edit }
        format.json { render json: @encargado_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encargado_compras/1
  # DELETE /encargado_compras/1.json
  def destroy
    @encargado_compra.destroy
    respond_to do |format|
      format.html { redirect_to encargado_compras_url, notice: 'Encargado compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encargado_compra
      @encargado_compra = EncargadoCompra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encargado_compra_params
      params.fetch(:encargado_compra, {})
    end
end

app/helpers/encargado_compras_helper.rb
module EncargadoComprasHelper
end

app/views/encargado_compras/_form.html.erb
<%= form_with(model: encargado_compra, local: true) do |form| %>
  <% if encargado_compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encargado_compra.errors.count, "error") %> prohibited this encargado_compra from being saved:</h2>

      <ul>
      <% encargado_compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/encargado_compras/edit.html.erb
<h1>Editing Encargado Compra</h1>

<%= render 'form', encargado_compra: @encargado_compra %>

<%= link_to 'Show', @encargado_compra %> |
<%= link_to 'Back', encargado_compras_path %>

app/views/encargado_compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encargado Compras</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encargado_compras.each do |encargado_compra| %>
      <tr>
        <td><%= link_to 'Show', encargado_compra %></td>
        <td><%= link_to 'Edit', edit_encargado_compra_path(encargado_compra) %></td>
        <td><%= link_to 'Destroy', encargado_compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encargado Compra', new_encargado_compra_path %>

app/views/encargado_compras/new.html.erb
<h1>New Encargado Compra</h1>

<%= render 'form', encargado_compra: @encargado_compra %>

<%= link_to 'Back', encargado_compras_path %>

app/views/encargado_compras/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_encargado_compra_path(@encargado_compra) %> |
<%= link_to 'Back', encargado_compras_path %>