config/routes.rb
Rails.application.routes.draw do
  get '/display', to: 'display_api#display'
  #####Seccion del API
  namespace :api do
    resources :orden_compras
  end
  #####
  get 'aux_bodobra', to: 'reg_aux#bodobra'
  get 'aux_bodcentral', to: 'reg_aux#bodcentral'
  get 'aux_personal', to: 'reg_aux#personal'
  post 'aux_bodobra', to: 'reg_aux#bo_create'
  post 'aux_bodcentral', to: 'reg_aux#bc_create'
  post 'aux_personal', to: 'reg_aux#po_create'
  get 'testmail', to: 'testmail#index'
  get '/materiales', to: 'materiales#index'
  get 'materiales/agregar'
  get 'materiales/peticion'
  get '/inventario', to: 'inventario#ver'
  get '/inventario/agregar', to: 'inventario#agregar'
  post '/inventario/agregar', to: 'inventario#add'
  get '/inventario/sacar', to: 'inventario#sacar'
  post '/inventario/sacar/update', to: 'inventario#update_sacar'
  post '/solicituds/:id/add', to: 'solicituds#add'
  post '/solicituds/:id/add_create', to: 'solicituds#add_create'
  post '/solicituds/:id/enviar', to: 'solicituds#enviar'
  post '/solicituds/responder', to: 'solicituds#responder'
  post '/solicituds/confirmar', to: 'solicituds#confirmar'
  post '/solicituds/confirmar/action', to: 'solicituds#action_confirmar'
  post '/solicituds/responder/envio', to: 'solicituds#envio_solicitud', defaults: { :format => 'json' }
  resources :materials
  resources :inventario_centrals
  resources :abastecimiento_obras
  resources :abastecimiento_centrals
  resources :bodega_centrals
  resources :inventario_obras
  resources :bodega_obras
  resources :proveedors
  resources :orden_compras
  resources :encargado_compras
  resources :bodeguero_centrals
  resources :bodeguero_obras
  resources :personal_obras
  resources :solicituds
  root    'static_pages#home'
  get     '/help', to: 'static_pages#help'
  get     '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup', to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
  get     '/operations', to: 'operations#center'
  get     'home/index'

  resources :users
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/abastecimiento_obra.rb
class AbastecimientoObra < ApplicationRecord
  belongs_to :bodega_obra
  belongs_to :proveedor
end

app/controllers/abastecimiento_obras_controller.rb
class AbastecimientoObrasController < ApplicationController
  before_action :set_abastecimiento_obra, only: [:show, :edit, :update, :destroy]

  # GET /abastecimiento_obras
  # GET /abastecimiento_obras.json
  def index
    @abastecimiento_obras = AbastecimientoObra.all
  end

  # GET /abastecimiento_obras/1
  # GET /abastecimiento_obras/1.json
  def show
  end

  # GET /abastecimiento_obras/new
  def new
    @abastecimiento_obra = AbastecimientoObra.new
  end

  # GET /abastecimiento_obras/1/edit
  def edit
  end

  # POST /abastecimiento_obras
  # POST /abastecimiento_obras.json
  def create
    @abastecimiento_obra = AbastecimientoObra.new(abastecimiento_obra_params)

    respond_to do |format|
      if @abastecimiento_obra.save
        format.html { redirect_to @abastecimiento_obra, notice: 'Abastecimiento obra was successfully created.' }
        format.json { render :show, status: :created, location: @abastecimiento_obra }
      else
        format.html { render :new }
        format.json { render json: @abastecimiento_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abastecimiento_obras/1
  # PATCH/PUT /abastecimiento_obras/1.json
  def update
    respond_to do |format|
      if @abastecimiento_obra.update(abastecimiento_obra_params)
        format.html { redirect_to @abastecimiento_obra, notice: 'Abastecimiento obra was successfully updated.' }
        format.json { render :show, status: :ok, location: @abastecimiento_obra }
      else
        format.html { render :edit }
        format.json { render json: @abastecimiento_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abastecimiento_obras/1
  # DELETE /abastecimiento_obras/1.json
  def destroy
    @abastecimiento_obra.destroy
    respond_to do |format|
      format.html { redirect_to abastecimiento_obras_url, notice: 'Abastecimiento obra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abastecimiento_obra
      @abastecimiento_obra = AbastecimientoObra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abastecimiento_obra_params
      params.fetch(:abastecimiento_obra, {})
    end
end

app/helpers/abastecimiento_obras_helper.rb
module AbastecimientoObrasHelper
end

app/views/abastecimiento_obras/_form.html.erb
<%= form_with(model: abastecimiento_obra, local: true) do |form| %>
  <% if abastecimiento_obra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(abastecimiento_obra.errors.count, "error") %> prohibited this abastecimiento_obra from being saved:</h2>

      <ul>
      <% abastecimiento_obra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abastecimiento_obras/edit.html.erb
<h1>Editing Abastecimiento Obra</h1>

<%= render 'form', abastecimiento_obra: @abastecimiento_obra %>

<%= link_to 'Show', @abastecimiento_obra %> |
<%= link_to 'Back', abastecimiento_obras_path %>

app/views/abastecimiento_obras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abastecimiento Obras</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abastecimiento_obras.each do |abastecimiento_obra| %>
      <tr>
        <td><%= link_to 'Show', abastecimiento_obra %></td>
        <td><%= link_to 'Edit', edit_abastecimiento_obra_path(abastecimiento_obra) %></td>
        <td><%= link_to 'Destroy', abastecimiento_obra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Abastecimiento Obra', new_abastecimiento_obra_path %>

app/views/abastecimiento_obras/new.html.erb
<h1>New Abastecimiento Obra</h1>

<%= render 'form', abastecimiento_obra: @abastecimiento_obra %>

<%= link_to 'Back', abastecimiento_obras_path %>

app/views/abastecimiento_obras/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_abastecimiento_obra_path(@abastecimiento_obra) %> |
<%= link_to 'Back', abastecimiento_obras_path %>