config/routes.rb
Rails.application.routes.draw do
  get '/display', to: 'display_api#display'
  #####Seccion del API
  namespace :api do
    resources :orden_compras
  end
  #####
  get 'aux_bodobra', to: 'reg_aux#bodobra'
  get 'aux_bodcentral', to: 'reg_aux#bodcentral'
  get 'aux_personal', to: 'reg_aux#personal'
  post 'aux_bodobra', to: 'reg_aux#bo_create'
  post 'aux_bodcentral', to: 'reg_aux#bc_create'
  post 'aux_personal', to: 'reg_aux#po_create'
  get 'testmail', to: 'testmail#index'
  get '/materiales', to: 'materiales#index'
  get 'materiales/agregar'
  get 'materiales/peticion'
  get '/inventario', to: 'inventario#ver'
  get '/inventario/agregar', to: 'inventario#agregar'
  post '/inventario/agregar', to: 'inventario#add'
  get '/inventario/sacar', to: 'inventario#sacar'
  post '/inventario/sacar/update', to: 'inventario#update_sacar'
  post '/solicituds/:id/add', to: 'solicituds#add'
  post '/solicituds/:id/add_create', to: 'solicituds#add_create'
  post '/solicituds/:id/enviar', to: 'solicituds#enviar'
  post '/solicituds/responder', to: 'solicituds#responder'
  post '/solicituds/confirmar', to: 'solicituds#confirmar'
  post '/solicituds/confirmar/action', to: 'solicituds#action_confirmar'
  post '/solicituds/responder/envio', to: 'solicituds#envio_solicitud', defaults: { :format => 'json' }
  resources :materials
  resources :inventario_centrals
  resources :abastecimiento_obras
  resources :abastecimiento_centrals
  resources :bodega_centrals
  resources :inventario_obras
  resources :bodega_obras
  resources :proveedors
  resources :orden_compras
  resources :encargado_compras
  resources :bodeguero_centrals
  resources :bodeguero_obras
  resources :personal_obras
  resources :solicituds
  root    'static_pages#home'
  get     '/help', to: 'static_pages#help'
  get     '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup', to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
  get     '/operations', to: 'operations#center'
  get     'home/index'

  resources :users
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/bodega_central.rb
class BodegaCentral < ApplicationRecord
  has_many :bodeguero_obras
  has_one :bodeguero_central, -> { includes :user }
  has_many :inventario_centrals
  has_many :abastecimiento_centrals
  has_many :solicituds
end

app/controllers/bodega_centrals_controller.rb
class BodegaCentralsController < ApplicationController
  before_action :set_bodega_central, only: [:show, :edit, :update, :destroy]

  # GET /bodega_centrals
  # GET /bodega_centrals.json
  def index
    @bodega_centrals = BodegaCentral.all
  end

  # GET /bodega_centrals/1
  # GET /bodega_centrals/1.json
  def show
  end

  # GET /bodega_centrals/new
  def new
    @bodega_central = BodegaCentral.new
  end

  # GET /bodega_centrals/1/edit
  def edit
  end

  # POST /bodega_centrals
  # POST /bodega_centrals.json
  def create
    @bodega_central = BodegaCentral.new(bodega_central_params)

    respond_to do |format|
      if @bodega_central.save
        format.html { redirect_to @bodega_central, notice: 'Bodega central was successfully created.' }
        format.json { render :show, status: :created, location: @bodega_central }
      else
        format.html { render :new }
        format.json { render json: @bodega_central.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodega_centrals/1
  # PATCH/PUT /bodega_centrals/1.json
  def update
    respond_to do |format|
      if @bodega_central.update(bodega_central_params)
        format.html { redirect_to @bodega_central, notice: 'Bodega central was successfully updated.' }
        format.json { render :show, status: :ok, location: @bodega_central }
      else
        format.html { render :edit }
        format.json { render json: @bodega_central.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodega_centrals/1
  # DELETE /bodega_centrals/1.json
  def destroy
    @bodega_central.destroy
    respond_to do |format|
      format.html { redirect_to bodega_centrals_url, notice: 'Bodega central was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bodega_central
      @bodega_central = BodegaCentral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bodega_central_params
      params.fetch(:bodega_central, {})
    end
end

app/helpers/bodega_centrals_helper.rb
module BodegaCentralsHelper
end

app/views/bodega_centrals/_form.html.erb
<%= form_with(model: bodega_central, local: true) do |form| %>
  <% if bodega_central.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bodega_central.errors.count, "error") %> prohibited this bodega_central from being saved:</h2>

      <ul>
      <% bodega_central.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bodega_centrals/edit.html.erb
<h1>Editing Bodega Central</h1>

<%= render 'form', bodega_central: @bodega_central %>

<%= link_to 'Show', @bodega_central %> |
<%= link_to 'Back', bodega_centrals_path %>

app/views/bodega_centrals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bodega Centrals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodega_centrals.each do |bodega_central| %>
      <tr>
        <td><%= link_to 'Show', bodega_central %></td>
        <td><%= link_to 'Edit', edit_bodega_central_path(bodega_central) %></td>
        <td><%= link_to 'Destroy', bodega_central, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bodega Central', new_bodega_central_path %>

app/views/bodega_centrals/new.html.erb
<h1>New Bodega Central</h1>

<%= render 'form', bodega_central: @bodega_central %>

<%= link_to 'Back', bodega_centrals_path %>

app/views/bodega_centrals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bodega_central_path(@bodega_central) %> |
<%= link_to 'Back', bodega_centrals_path %>