config/routes.rb
Rails.application.routes.draw do
  get '/display', to: 'display_api#display'
  #####Seccion del API
  namespace :api do
    resources :orden_compras
  end
  #####
  get 'aux_bodobra', to: 'reg_aux#bodobra'
  get 'aux_bodcentral', to: 'reg_aux#bodcentral'
  get 'aux_personal', to: 'reg_aux#personal'
  post 'aux_bodobra', to: 'reg_aux#bo_create'
  post 'aux_bodcentral', to: 'reg_aux#bc_create'
  post 'aux_personal', to: 'reg_aux#po_create'
  get 'testmail', to: 'testmail#index'
  get '/materiales', to: 'materiales#index'
  get 'materiales/agregar'
  get 'materiales/peticion'
  get '/inventario', to: 'inventario#ver'
  get '/inventario/agregar', to: 'inventario#agregar'
  post '/inventario/agregar', to: 'inventario#add'
  get '/inventario/sacar', to: 'inventario#sacar'
  post '/inventario/sacar/update', to: 'inventario#update_sacar'
  post '/solicituds/:id/add', to: 'solicituds#add'
  post '/solicituds/:id/add_create', to: 'solicituds#add_create'
  post '/solicituds/:id/enviar', to: 'solicituds#enviar'
  post '/solicituds/responder', to: 'solicituds#responder'
  post '/solicituds/confirmar', to: 'solicituds#confirmar'
  post '/solicituds/confirmar/action', to: 'solicituds#action_confirmar'
  post '/solicituds/responder/envio', to: 'solicituds#envio_solicitud', defaults: { :format => 'json' }
  resources :materials
  resources :inventario_centrals
  resources :abastecimiento_obras
  resources :abastecimiento_centrals
  resources :bodega_centrals
  resources :inventario_obras
  resources :bodega_obras
  resources :proveedors
  resources :orden_compras
  resources :encargado_compras
  resources :bodeguero_centrals
  resources :bodeguero_obras
  resources :personal_obras
  resources :solicituds
  root    'static_pages#home'
  get     '/help', to: 'static_pages#help'
  get     '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup', to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
  get     '/operations', to: 'operations#center'
  get     'home/index'

  resources :users
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/orden_compra.rb
class OrdenCompra < ApplicationRecord
  #include HTTParty
  belongs_to :proveedor, dependent: :destroy
  belongs_to :encargado_compra, dependent: :destroy
  has_many :registro_materials, :dependent => :destroy
  accepts_nested_attributes_for :registro_materials, :reject_if => lambda {|a| a[:nombre_item].blank? && a[:sku].blank? && a[:cantidad].blank? && a[:precio].blank?}, :allow_destroy => true
end

app/controllers/api/orden_compras_controller.rb
class Api::OrdenComprasController < ApplicationController
  before_action :set_orden_compra

  def show
  end

  private

    def set_orden_compra
      @orden_compra = OrdenCompra.find(params[:id])
    end
end

app/controllers/orden_compras_controller.rb
class OrdenComprasController < ApplicationController
  before_action :set_orden_compra , only: [:show, :edit, :update, :destroy]
  before_action :EncargadoCompra_all, :Proveedor_all

  def Proveedor_all
    @proveedor_data = Proveedor.all.ids
  end

  def EncargadoCompra_all
    @EC_data = EncargadoCompra.all.ids
  end
  # GET /orden_compras
  # GET /orden_compras.json
  def index
    @orden_compras = OrdenCompra.all
  end

  # GET /orden_compras/1
  # GET /orden_compras/1.json
  def show
    @orden_compras = OrdenCompra.find(params[:id])

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @orden_compras }
    end
  end

  # GET /orden_compras/new
  def new
    @orden_compra = OrdenCompra.new
    @orden_compra.registro_materials.build
  end

  # GET /orden_compras/1/edit
  def edit
  end

  # POST /orden_compras
  # POST /orden_compras.json
  def create
    @orden_compra = OrdenCompra.new(orden_compra_params)

    respond_to do |format|
      if @orden_compra.save
        format.html { redirect_to @orden_compra, notice: 'Orden compra was successfully created.' }
        format.json { render :show, status: :created, location: @orden_compra }
      else
        format.html { render :new }
        format.json { render json: @orden_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orden_compras/1
  # PATCH/PUT /orden_compras/1.json
  def update
    respond_to do |format|
      if @orden_compra.update(orden_compra_params)
        format.html { redirect_to @orden_compra, notice: 'Orden compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden_compra }
      else
        format.html { render :edit }
        format.json { render json: @orden_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orden_compras/1
  # DELETE /orden_compras/1.json
  def destroy
    @orden_compra.destroy
    respond_to do |format|
      format.html { redirect_to orden_compras_url, notice: 'Orden compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden_compra
      @orden_compra = OrdenCompra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_compra_params
      params.require(:orden_compra).permit(:numero_orden, :proveedor_id, :encargado_compra_id, :nombre_item, :sku, :cantidad,
      registro_materials_attributes: [:id, :nombre_item, :sku, :cantidad, :precio, :descripcion])
    end

end

app/helpers/orden_compras_helper.rb
module OrdenComprasHelper
end

app/views/orden_compras/_form.html.erb
<%= nested_form_for @orden_compra do |form| %>
  <% if orden_compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden_compra.errors.count, "error") %> prohibited this orden_compra from being saved:</h2>

      <ul>
      <% orden_compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :numero_orden %>
  <%= form.text_field :numero_orden, class: 'form-control' %>

  <%= form.label :proveedor_id %>
  <%= form.select(:proveedor_id, @proveedor_data) %>

  <%= form.label :encargado_compra_id %>
  <%= form.select(:encargado_compra_id, @EC_data) %>

  <p><%= form.link_to_add "Agregar Material", :registro_materials %></p>

  <% form.fields_for :registro_materials do |builder| %>

  <p>
    <%= builder.label :nombre_item %>
    <%= builder.text_field :nombre_item, class: 'form-control' %>

    <%= builder.label :sku %>
    <%= builder.text_field :sku, class: 'form-control' %>

    <%= builder.label :cantidad %>
    <%= builder.text_field :cantidad, class: 'form-control' %>

    <%= builder.label :precio %>
    <%= builder.text_field :precio, class: 'form-control' %>

    <%= builder.label :descripcion %>
    <%= builder.text_area :descripcion, :rows => 3 %>
  </p>

  <%= builder.link_to_remove "Quitar Material" %>

  <% end %>

  <%= form.submit "Generar Orden", class: "btn btn-primary" %>

<% end %>

app/views/orden_compras/_registro_material_fields.html.erb
<p class="fields">
  <p>
    <%= f.label :nombre_item %>
    <%= f.text_field :nombre_item, class: 'form-control' %>

    <%= f.label :sku %>
    <%= f.text_field :sku, class: 'form-control' %>

    <%= f.label :cantidad %>
    <%= f.text_field :cantidad, class: 'form-control' %>

    <%= f.label :precio %>
    <%= f.text_field :precio, class: 'form-control' %>

    <%= f.label :descripcion %>
    <%= f.text_area :descripcion, :rows => 3 %>
  </p>

  <%= link_to_remove_fields "remove", f %>
</p>

app/views/orden_compras/edit.html.erb
<h1>Editing Orden Compra</h1>

<%= render 'form', orden_compra: @orden_compra %>

<%= link_to 'Show', @orden_compra %> |
<%= link_to 'Back', orden_compras_path %>

app/views/orden_compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orden Compras</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orden_compras.each do |orden_compra| %>
      <tr>
        <td><%=  orden_compra.numero_orden %></td>
        <td><%= link_to 'Show', orden_compra %></td>
        <td><%= link_to 'Edit', edit_orden_compra_path(orden_compra) %></td>
        <td><%= link_to 'Destroy', orden_compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul>
<li><%= link_to 'New Orden Compra', new_orden_compra_path %></li>
<br>

<li><%= link_to 'Ver Ordenes de Compra Remotas', display_path %></li>
</ul>

app/views/orden_compras/new.html.erb
<h1>New Orden Compra</h1>

<%= render 'form', orden_compra: @orden_compra %>

<%= link_to 'Back', orden_compras_path %>

app/views/orden_compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numero Orden:</b>
  <%= @orden_compra.numero_orden %>
</p>

<p>
  <b>ID Proveedor:</b>
  <%= @orden_compra.proveedor_id %>
</p>

<p>
  <b>ID Encargado de Compra:</b>
  <%= @orden_compra.encargado_compra_id %>
</p>


<%= link_to 'Edit', edit_orden_compra_path(@orden_compra) %> |
<%= link_to 'Back', orden_compras_path %>